### ISSUE TITLE
ankiserver.pid NOT Found but can ankiserverctl.py in debug mode.

### ISSUE THREAD

**Issue by lali123456** [tsudoko/anki-sync-server#1]
C:\Python34\Scripts>python ankiserverctl.py start
Traceback (most recent call last):
  File "ankiserverctl.py", line 165, in <module>
    main()
  File "ankiserverctl.py", line 145, in main
    startsrv(sys.argv[2], False)
  File "ankiserverctl.py", line 50, in startsrv
    with open(PIDPATH, "w") as pidfile:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ankiserver.pid'

**Comment by tsudoko** [comment]
Try the `anki21_windows` branch. I don't have a Windows machine at hand to test it, so I can't guarentee it works, though.
