### ISSUE TITLE
Adding Docker support

### ISSUE THREAD

**Issue by kuklinistvan** [tsudoko/anki-sync-server#16]
I have created a Docker image based on your work sometime before and I am curious if it could be merged or linked to your repository to centralise our efforts as one of your contributors suggested:
https://github.com/kuklinistvan/docker-anki-sync-server/issues/2

Also, I'd like to say thank you to you for maintaining ankisyncd as well as to all the contributors!

**Comment by tsudoko** [comment]
I put a link in the README. You seem to be much better at maintaining this than I would be (I don't know anything about Docker at all), so I think it's a good solution.
