### ISSUE TITLE
code 400, message Bad request version ('À')

### ISSUE THREAD

**Issue by DreamFlasher** [tsudoko/anki-sync-server#17]
I use AnkiDroid 2.8.5beta1
and get `code 400, message Bad request version ('À')`
on the sync server console output log. So I configured my client correctly (it reaches the server).

**Comment by luoliyan** [comment]
What protocol are you using to sync? I ran into something similar the other day. If you've given an `https` URL to AnkiDroid, try changing it to `http`.

**Comment by DreamFlasher** [comment]
Thank you, yes that solves it, the protocol needs to be http. I'd suggest that the code should be upgraded to use https.

**Comment by tsudoko** [comment]
The server does work with HTTPS, you just need to [set up a reverse proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) for `http://localhost:27701` (or whatever port you have set in the config file) on an HTTPS-capable web server.
