### ISSUE TITLE
AnkiDroid: Error syncing media data

### ISSUE THREAD

**Issue by DreamFlasher** [tsudoko/anki-sync-server#18]
I am trying to synchronize with anki-sync-server for the first time, the collections have been synchronized with AnkiWeb before.
I get `Error syncing media data` `org.json.JSONException: Value Anki of type java.lang.String cannot be converted to JSONObject`.

**Comment by tsudoko** [comment]
What URLs do you have in your settings? AnkiDroid doesn't strip trailing slashes from media sync URLs, so you need to remove them if they're there.

**Comment by DreamFlasher** [comment]
That fixes the issue. In the installation guide it has trailing slashes, so I assumed that AnkiDroid needs the same. I created a PR to adding the necessary documentation. https://github.com/tsudoko/anki-sync-server/pull/22
