### ISSUE TITLE
Add support for only syncing selected profiles with the Custom Sync Server in the addon

### ISSUE THREAD

**Issue by AntonOfTheWoods** [tsudoko/anki-sync-server#19]
For my usecase it would be great for users to be able to sync with the custom server for only a subset of their profiles. That way they can continue syncing with ankiweb for some of their profiles, and with the custom server for the others. By default the behaviour stays as it is now (sync all with the custom server if it's activated).

**Comment by tsudoko** [comment]
Implemented in 4214fc3da07a1c53fec7b8646932008b9b7abe14
