### ISSUE TITLE
Error on full sync upload

### ISSUE THREAD

**Issue by colonelsmoothie** [tsudoko/anki-sync-server#2]
Hello,

I've been testing this out with Anki 2.1.0 beta 4. Whenever I make a change to my deck that requires a full sync upload, like changing a note type, I get the following error:

```
Syncing failed:
Traceback (most recent call last):
  File "aqt/sync.py", line 340, in run
  File "aqt/sync.py", line 396, in _sync
  File "aqt/sync.py", line 425, in _fullSync
  File "anki/sync.py", line 680, in upload
  File "anki/sync.py", line 565, in req
  File "anki/sync.py", line 510, in assertOk
Exception: Unknown response code: 400
```

Full sync downloads work okay for me.

Thanks

**Comment by colonelsmoothie** [comment]
Another beta tester is having sync problems with the actual Ankiweb, so the problem may be on Anki's side:

http://anki.tenderapp.com/discussions/beta-testing/639-anki-210-beta4-crashing-during-syncing

Damien said a fix will be in the next release, although I'm not sure if this is the same issue I'm having. I'll be on the lookout when beta 5 comes out.

**Comment by tsudoko** [comment]
Also https://anki.tenderapp.com/discussions/beta-testing/647-full-upload-fails.
Official beta 4 builds crash on start for me and my distro's pyqt and python versions are too old, so my testing possibilities are limited. I've reported the crash, we'll have to wait.

**Comment by tsudoko** [comment]
I was able to reproduce the issue and fix it on my end. Can you update and check if it still occurs?

**Comment by colonelsmoothie** [comment]
I've tried the beta26, but unfortunately I've got a new problem. I've built Anki from source and installed and configured the sync server, but Anki sync just isn't syncing with anki-sync-server. When I type in my credentials, I get a message saying that I've got an invalid password. But, if I try to sync with Ankiweb, it works...but only with Ankiweb.

Can you see if you have a similar problem?

Thanks again for all this!

**Comment by colonelsmoothie** [comment]
Alright, I think I figured it out. At some point, Damien changed the way the addons were read:

https://apps.ankiweb.net/docs/addons21.html

I figured out how to get it syncing, but since this is a different problem entirely I'll create a new issue, and I think we should close this one.
