### ISSUE TITLE
Could we know how to stop the anki-server?

### ISSUE THREAD

**Issue by JackalJohn** [tsudoko/anki-sync-server#25]
Sometimes anki-server may encounter some accidental bug causing no connection, and I need to restart it, but there is no command to stop the server. So I can only kill it or reboot the Linux. Is there a python command can stop or restart the server?

**Comment by tsudoko** [comment]
Killing it is the right way, just don't do it with `SIGKILL`. Or when you're syncing. Alternatively you can use ctrl-c if you're running the server from an interactive shell.
