### ISSUE TITLE
Long media sync times

### ISSUE THREAD

**Issue by genedan** [tsudoko/anki-sync-server#26]
Is anyone noticing a long sync time for media changes, for those of you who have a large collection? It's 15 minutes on my end. Sometimes it fails, so I have to resync and wait another 15 min, etc. 

To reproduce the issue, simply have a large media collection (I have 40k files), make some media changes, and then sync.

I'm not sure if the issue is on the side of AnkiDroid or ankisyncd, just my observations.

**Comment by AntonOfTheWoods** [comment]
Off the top of my head,  found what I think are a few bugs with upstream code that might be related. What is the server thread doing during this time? Do you have any logs you could share?

**Comment by tsudoko** [comment]
Even with ~3k media in my collection I encounter this too, but only on AnkiDroid. It's quite fast on the desktop version. I have my collection on an external SD card, though, which is not officially supported on AnkiDroid<sup>[1][]</sup>, so I decided not to report it.

[1]: https://github.com/ankidroid/Anki-Android/wiki/FAQ#my-ankidroid-files-are-stored-on-a-sd-card-how-can-i-point-ankidroid-to-them

**Comment by LapisLazulis** [comment]
Same happens to me too and like tsudoko, only on AnkiDroid! :)

**Comment by tsudoko** [comment]
Might be related: https://github.com/ankidroid/Anki-Android/issues/5261

**Comment by genedan** [comment]
My collection log file looks like @tsudoko 's, except mine has about 70,000 lines of checking media checks, so I suppose it goes through the entire media folder one file at a time.

Is this an issue worth raising at AnkiDroid? I have my collection stored in internal storage.

**Comment by tsudoko** [comment]
Workaround: #44
