### ISSUE TITLE
anki windows fails to sync. TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by shiftyshady** [tsudoko/anki-sync-server#34]
I am running latest anki-sync-server and latest (2.1.12) windows app.

I am not the only one encountering this issue:
https://github.com/dsnopek/anki-sync-server/issues/78
![1](https://user-images.githubusercontent.com/30387970/57196953-883d4500-6f59-11e9-9a5d-d7f8acec9cc0.jpg)

Edit: I no longer get this error (see below)

**Comment by tsudoko** [comment]
What's the full stack trace? How does your sync server addon code look like?

**Comment by shiftyshady** [comment]
import anki.sync

addr = "http://192.168.43.1:27701/" # put your server address here
anki.sync.SYNC_BASE = "%s" + addr

**Comment by shiftyshady** [comment]
`import anki.sync

addr = "http://xxx.xxx.xxx.xxx:27701/" # put your server address here
anki.sync.SYNC_BASE = "%s" + addr`

**Comment by shiftyshady** [comment]
![1](https://user-images.githubusercontent.com/30387970/57192644-b192ac80-6f2a-11e9-901a-fc82fa16103e.jpg)

**Comment by tsudoko** [comment]
What's in the server log? Does it log any requests at all?

**Comment by shiftyshady** [comment]
sorry. anki-sync-server seemed to launch without problems, but when I run "./ankisyncctl.py adduser whatever" I get: "./ankisyncctl.py line 32; print("Could not delete user {}: {}:.format(username, error), filsys.stderror)"

**Comment by shiftyshady** [comment]
the error on the server when I try to sync is: 
![3](https://user-images.githubusercontent.com/30387970/57196889-f9c8c380-6f58-11e9-87a3-da2c45b41fa7.jpg)

I have cleaned up previous posts because the errors I am getting now are different. I no longer get "TypeError: not all arguments converted during string formatting" but instead: "syncing failed: Ankiweb encountered an error. Please try again in a.."

**Comment by tsudoko** [comment]
You need to run ankisyncctl.py with Python 3. If your OS' default Python isn't 3.x, but you do have Python 3 installed, `python3 ankisyncctl.py [stuff you want to do]` should do the job.

The error you get on the server side should disappear once you have succesfully added a user.

**Comment by shiftyshady** [comment]
Thanks. I had to delete auth.db and session.db for it to work, so you were most likely spot-on, I probably forgot the "3" in "python3" when I added a user the first time a few days ago.
