### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by colonelsmoothie** [tsudoko/anki-sync-server#4]
Hello,

I'm trying to get things set up using the master branch. I followed the instructions, but I'm getting stuck on step 3:

![image](https://user-images.githubusercontent.com/3887707/44316101-60b84380-a3ef-11e8-9996-b3594454a01f.png)

Here's what I've got in my ankysyncd.conf file:

![image](https://user-images.githubusercontent.com/3887707/44316112-788fc780-a3ef-11e8-91f3-34c46248a0fc.png)

Any thoughts on where to proceed from here?

Thanks

**Comment by tsudoko** [comment]
Try again after updating to latest master. `master` is my personal branch, so it's a bit messy.

**Comment by colonelsmoothie** [comment]
Aright, I see it now. auth.db is now created in the repo directory.
