### ISSUE TITLE
Checking database while having freshly added cards in a deck causes inconsistency

### ISSUE THREAD

**Issue by kuklinistvan** [tsudoko/anki-sync-server#41]
Hey tsudoku,

I am not sure if I should this report to you or directly to the developers of Anki Desktop, but I have encountered an interesting behavior that can break syncing, while I was about to update the image to support the latest version of Anki.

Anki Desktop version: 2.1.14
`ankisyncd` version: 7ef3d4f on master

Reproduction:
1. Set up `ankisyncd` and point an Anki Desktop instance to it
2. Create a deck and some cards, maybe manipulate them
3. Synchronize making sure it works at this point
4. Ensure that you have at least one completely fresh, unreviewed card
It should look as follows in the browser:
![due1000000](https://user-images.githubusercontent.com/19473224/60810107-95aac180-a18c-11e9-9477-fe08ff2e6d32.png)

5. Synchronize again - it should still work
6. BREAK IT: Hit Check datatabase...

A message similar to this one should appear:
Found 1 new cards with a due number >= 1,000,000 - consider repositioning them in the Browse screen.
Database rebuilt and optimized.

7. Sync again - now it is broken
![inconsistent](https://user-images.githubusercontent.com/19473224/60810227-e3272e80-a18c-11e9-8b5d-c4cd22371b07.png)

The server output does not seem to contain too much useful information at the very moment this message appears on the client side:

```
[2019-07-08 12:31:20,928]:INFO:ankisyncd.CollectionThread[sajat_anki]:Running meta(*[], **{'v': 9, 'cv': 'ankidesktop,2.1.14 (7b93e985),lin:arch:rolling'})
[2019-07-08 12:31:20,930]:INFO:ankisyncd.http:172.17.0.1 "POST /sync/meta HTTP/1.1" 200 112
```

What do you think, is it related to `ankisyncd` or should I forward this bug to the developers of Anki Desktop?

Best regards,
István

**Comment by tsudoko** [comment]
Are you still able to reproduce this? Does the due number change to 1000000 right after syncing or is the change caused by something else than sync?

**Comment by kuklinistvan** [comment]
Thank you for investigating the root of the problem!

Good news - I've tested this behavior with Anki Desktop version 2.1.19. 

![Képernyőkép_2020-02-03_16-43-19](https://user-images.githubusercontent.com/19473224/73667281-57cf3680-46a4-11ea-92b6-0de65710a726.png)

In this version a new card does not receive a due value of 1000000 but rather the next one from a sequence starting from 1, as seen in the attached picture.

The error message does not appear and the consistency is not broken. 

Before closing this issue, I'm doing [some manual tests](https://github.com/kuklinistvan/docker-anki-sync-server/blob/testing/Testing.md) to see whether `ankisyncd` is capable of handling version 2.1.19 already.

**Comment by kuklinistvan** [comment]
Oh no, I see it again.

I was synchronizing the cards back and forth and it happened again :(

AnkiDroid version 2.9.1 and Anki Desktop 2.1.19

![Képernyőkép_2020-02-03_17-15-22](https://user-images.githubusercontent.com/19473224/73670012-c57d6180-46a8-11ea-9d70-5b60c4e1ce1e.png)

Did not find out how to reproduce it yet...

**Comment by kuklinistvan** [comment]
Well, it became harder to reproduce and mostly I am able to test it without running into this problem.

Because it now occurs only very rarely and not in a special predictable way like before, I'm releasing a new Docker image.

Thanks again for maintaining `ankisyncd`, it is an awesome project!
