### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gjabell** [tsudoko/anki-sync-server#46]
It's been 3 years since the last release, and I would prefer to use release versions when packaging ankisyncd. Any chance you could bump the release version to incorporate the changes in the past few years sometime soon?

Thanks!

**Comment by tsudoko** [comment]
Here you go: https://github.com/tsudoko/anki-sync-server/releases/tag/2.1.0
The `ankisyncd-2.1.0.tar.gz` file included with the release is a snapshot of the source tree with the `anki-bundled` submodule cloned and an additional `ankisyncd/_version.py` file containing Git-independent version.

**Comment by gjabell** [comment]
Thanks!
