### ISSUE TITLE
Local server data is not cleared

### ISSUE THREAD

**Issue by ghost** [tsudoko/anki-sync-server#59]
After deleting the PC version of Anki data, sync the private server again, it shows that the synchronization is correct, but the private server data is not cleared

Environmental description:
os: Windows7
PC anki version: 2.1.20
Python version ：3.6

**Comment by AntonOfTheWoods** [comment]
What do you mean by "the private server data is not cleared"? You mean that that the synchronisation wasn't, in fact, correct?

**Comment by ghost** [comment]
I  know the  answer. it's  not a    question
