### ISSUE TITLE
client using unsupported protocol (10,support 9) on Windows anki(2.1.22)

### ISSUE THREAD

**Issue by dobefore** [tsudoko/anki-sync-server#62]
PC: Win 10 ,PC anki version:2.1.22 (0ecc189a) 
when everything done ,it says,
`your client is using unsupported sync protocol(10,supported version:9)`
 ,PC anki `version 2.1.21` is running perfect!y thanks to @mrozigor  's instructions of his PR  any help would be appreciated !
![2020-03-25_111309](https://user-images.githubusercontent.com/46564102/77500890-4f6bce80-6e91-11ea-935d-5f480cb710bb.jpg)
when i close it,another window appears,it says,`username or passwd wrong ,retry`
![2020-03-25_111402](https://user-images.githubusercontent.com/46564102/77500924-69a5ac80-6e91-11ea-980a-dece074665b9.jpg)

**Comment by jku1995** [comment]
The last avaliable version is 2.1.15.

**Comment by mrozigor** [comment]
Did you tried to make this change on server - https://github.com/tsudoko/anki-sync-server/issues/63#issuecomment-609768430 ?

**Comment by dobefore** [comment]
@mrozigor  How kind of you It is! With me following your newest PR,It works perfectly on Win10 Anki version
`2.1.25` (What a fast speed the anki develping version is!). Sincerely Thank you for PR! In my case,editing of addon` __init__.py`, 
`anki.sync.SYNC_BASE = "%.0s" + addr`
this is true in my case (It seemingly That is also the thing you told of,but 
not compitable with #63
