### ISSUE TITLE
Cannot sync with anki 2.1.23

### ISSUE THREAD

**Issue by ghost** [tsudoko/anki-sync-server#63]
anki 2.1.23 being in archlinux' community-testing repo, I tried to upgrade to it from 2.1.15. Everything is fine except I get an error message when opening it to sync with anki-sync-server.

`Your client is using unsupported sync protocol (10, supported version: 9)`

I saw that anki-sync-server only supports anki up to 2.1.16. Is there a way to get newer versions to be included ?

**Comment by mrozigor** [comment]
I locally, on my server, changed file `ankisyncd/sync_app.py:86` from `if v > SYNC_VER:` to `if v > 10`. I didn't check it for now, but it seems to work correctly (with my other changes from PR).

**Comment by mrozigor** [comment]
I think that it can be serious problem with Anki 2.1.24, due to some changes in database, connected with config. When it will work locally, then I try to update my PR with proper changes on anki-sync-server.

**Comment by galantra** [comment]
Possible workaround: Use a supported version of Anki for syncing, switch back to the recent version of Anki for everything else.

**Comment by ghost** [comment]
So I updated anki to v2.1.23 and followed @mrozigor instructions. Everything works now. An error message : `AnkiWeb ID or password is incorrect; please try again` get triggered each time I sync but it doesn't seem to affect the process.

**Comment by ghost** [comment]
Actually, I checked and while syncing cards seems to work, it can't sync medias. So the issue is still there.

**Comment by mrozigor** [comment]
Did you try to apply changes from https://github.com/tsudoko/anki-sync-server/pull/60 as well as above change with SYNC_VER?

**Comment by mrozigor** [comment]
Didn't realize that you make those changes. Did you also add proper entries in addon `__init__.py` file:
```
(...)
addr = "http://IP:PORT/"
anki.sync.SYNC_BASE = "%s" + addr
aqt.mediasync.SYNC_BASE = "%s" + addr
(...)
```
?

**Comment by ghost** [comment]
That fixed it, thank you !

**Comment by bartowski-l** [comment]
@mrozigor please help me ! how to fix desktop app 2.1.26 username or passwd wrong ,retry? thank you so much

**Comment by mrozigor** [comment]
Which commit? Just before major code refactor in Anki? Do you have maybe more info about error?

**Comment by bartowski-l** [comment]
@mrozigor  thank you mrozigor! i have fix the problem.   i reference the #60.  just before major code. i put your code to the program. and it can be work .so i fix it. thank you so much to share the code.
