### ISSUE TITLE
AnkiWeb ID or password is incorrect; please try again

### ISSUE THREAD

**Issue by genedan** [tsudoko/anki-sync-server#64]
On Anki 2.1.24, every time I sync, I get a message that the password is incorrect. The collection still seems to sync, though.

Also mentioned in #63 

and

https://github.com/kuklinistvan/docker-anki-sync-server/issues/15

I've moved back to 2.1.21, which still works.

**Comment by dobefore** [comment]
It works fine with @mrozigor 's PR mentioned in #63 on Win10 Anki `2.1.25 `,where I tested. Is your editing correct?

**Comment by genedan** [comment]
I applied the changes in the PR and it works for me. I'm using Ubuntu 20.04 and tested it on Anki 2.1.25 just now. Thanks!
