### ISSUE TITLE
Anki desktop 2.1.26 doesn't sync

### ISSUE THREAD

**Issue by ghost** [tsudoko/anki-sync-server#66]
After updating to the new version, I got this error message while trying to sync : 
`Syncing failed:
AnkiWeb encountered an error. Please try again in a few minutes, and if the problem persists, please file a bug report.`

I was on version 2.1.23 before and it was working thanks to #63

**Comment by genedan** [comment]
2.1.26 is working for me in ubuntu. What output are you seeing in the terminal?

If you try rolling back to 2.1.23, does it work?

**Comment by ghost** [comment]
I see this in the terminal when I launch Anki 2.1.26 on archlinux : 
```
reverting to stock json
qt: using qt5ct plugin
qt: D-Bus global menu: no
qt: palette support is disabled
qt: custom style sheet is disabled
```
When I revert back to 2.1.23, there is also an error message : 
```
Anki was unable to open your collection file. If problems persist after restarting your computer, please use the Open Backup button in the profile manager.

Debug info:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aqt/main.py", line 441, in loadCollection
    return self._loadCollection()
  File "/usr/lib/python3.8/site-packages/aqt/main.py", line 462, in _loadCollection
    self.col = Collection(cpath, log=True)
  File "/usr/lib/python3.8/site-packages/anki/storage.py", line 59, in Collection
    col = _Collection(db, backend=backend, server=server, log=log)
  File "/usr/lib/python3.8/site-packages/anki/collection.py", line 101, in __init__
    self.load()
  File "/usr/lib/python3.8/site-packages/anki/collection.py", line 196, in load
    self.conf = json.loads(conf)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Everything is back to normal if I restore an older backup. Here is the Anki's About info : 
```
Version 2.1.23 (anki-2.1.23)
Python 3.8.2 Qt 5.14.2 PyQt 5.14.2
```

**Comment by dobefore** [comment]
Maybe data conflict.  On your desktop,check database and media,then export all decks. And clear PC anki decks data and media as well as server data and media (collection), and ,lastly, import decks and sync

**Comment by josealberto4444** [comment]
Same error for me.

I deleted all data of Anki desktop and started from scratch. After that, it just says that the ID or password are incorrect and refuses to sync.

**Comment by josealberto4444** [comment]
EDIT: Ignore this comment, I hadn't restarted Anki after creating the plugin.

I tried also with all changes from #60 with the same result:

`AnkiWeb ID or password was incorrect; please try again.`

In fact, it seems that it doesn't try to connect to the server, because the error is almost instant and I cannot see any activity in the server log. Maybe the bug is in the Anki plugin for connecting to the server?

**Comment by josealberto4444** [comment]
I tried with the changes from #60 and got again the same error than at the beginning:

    Syncing failed:
    AnkiWeb encountered an error. Please try again in a few minutes, and if the problem persists, please file a bug report.

**Comment by genedan** [comment]
@josealberto4444 What version of anki-bundled are you using for the server? The latest version that I've confirmed for it to work is 2.1.23. Past that, there have been substantial library changes that are incompatible with this repo.

**Comment by ghost** [comment]
@genedan On my headless server (ubuntu 18.04), I use the anki bundled with the anki server (version 2.1.11 then) since installing a newer anki via package manager would pull a lot of dependencies. Do I need a newer version for the sync to work ?

**Comment by josealberto4444** [comment]
> @josealberto4444 What version of anki-bundled are you using for the server?

As @zimawho, the version bundled with this repo (patched without pyaudio). I don't think there are errors in the instalation of the server, as it works perfectly with AnkiDroid. It is a sort of incompatibility between Anki desktop and this server. I am using Archlinux.

**Comment by borodust** [comment]
I see this on a server side:
```
ERROR:ankisyncd.CollectionThread[borodust]:Unable to meta(*[], **{'v': 10, 'cv': 'ankidesktop,2.1.26 (arch-linux-2.1.26-1),lin:manjaro:20.0.1'}): invalid literal for int() with base 10: 'h-linux-2.1.26-1)'
```
`2.1.26 (arch-linux-2.1.26-1)` is an unexpected version value here, I guess.

**Comment by sparunakian** [comment]
@borodust There is an issue about this in the ArchLinux bug tracker: https://bugs.archlinux.org/task/66756

**Comment by amsaravi** [comment]
I had same problem and changed sync_app.py:62 as a temporary workaround:
```
        note = {"alpha": 0, "beta": 0, "rc": 0}
        client, version, platform = cv.split(',')

        # to fix manjaro problem
        if('(') in version:
            version = version.split(' ')[0]


        for name in note.keys():
```

**Comment by ghost** [comment]
@amsaravi your solution seems to solve the problem. I'll test it more thoroughly when I add new cards tomorrow.

**Comment by ghost** [comment]
After further tests, everything seems to work thanks to @amsaravi 's temporary fix. So I can close this issue
