### ISSUE TITLE
about anki-sync-server problem 

### ISSUE THREAD

**Issue by bartowski-l** [tsudoko/anki-sync-server#74]
Your client is using unsupported sync protocol (10, supported version: 9)  when i open the program , show me this is problem.i don't know how to fix this problem . who can teacher me think you so mach.

**Comment by dobefore** [comment]
The resolution to this problem is related to #63

**Comment by bartowski-l** [comment]
yes,thank you so much. but i have a another question  An error message : AnkiWeb ID or password is incorrect; please try again . i had to add 
addr = "http://IP:PORT/"
anki.sync.SYNC_BASE = "%s" + addr
aqt.mediasync.SYNC_BASE = "%s" + addr
these code i have add to README.md 
but the error message has show again.
how i can fix this problem 
pleace teacher me  thank you!

**Comment by bartowski-l** [comment]
and what's mean of PR

**Comment by bartowski-l** [comment]
@dobefore can you tell me you qq num? this problem make me cazy ?so can you help me?
