### ISSUE TITLE
about anki desktop 2.1.35

### ISSUE THREAD

**Issue by liu-hz** [tsudoko/anki-sync-server#80]
After installing anki desktop 2.1.35, the user name and password error will be displayed when logging in to the user name, but the user name and password have not changed. The version before anki desktop 2.1.35 can be used. How to deal with it, mine__ init__ The content of. Py is as follows. I don't know if it is a file problem. Please help me to see how to handle it. Thank you so much

**Comment by liu-hz** [comment]
import anki.sync, anki.hooks, aqt

addr = "http://172.28.17.22:27701/" # put your server address here
anki.sync.SYNC_BASE = "%s" + addr
aqt.mediasync.SYNC_BASE = "%s" + addr
def resetHostNum():
    aqt.mw.pm.profile['hostNum'] = None
anki.hooks.addHook("profileLoaded", resetHostNum)


this is my __init__

**Comment by liu-hz** [comment]
I changed mine__ init__ . py file, but now error decoding response will be prompted body:missing field 'hostnum' at line 1 column 113 I read the article about the modification, but there are many updates. I need to update which file on the server to solve this problem. If you know, please let me know. Thank you

**Comment by nulltoany** [comment]
I have the same problem, have you solved it please?

**Comment by liu-hz** [comment]
i fix it it about http1.0 you can use nginx

**Comment by liu-hz** [comment]
use nginx use http1.0
